package model;
// Generated 17/09/2014 04:18:51 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Agentes generated by hbm2java
 */
@Entity
@Table(name="agentes"
    ,catalog="bddsemaforo"
    , uniqueConstraints = @UniqueConstraint(columnNames="age_codigo") 
)
public class Agentes  implements java.io.Serializable {


     private int ageId;
     private String ageCodigo;
     private String ageDireccion;
     private Double ageLatitud;
     private Double ageLongitud;
     private String ageFase;
     private String ageEstado;
     private String ageSentido;
     private String ageTipoluz;
     private Integer ageNorte;
     private Integer ageSur;
     private Integer ageEste;
     private Integer ageOeste;
     private String ageObservacion;

    public Agentes() {
    }

	
    public Agentes(int ageId, String ageCodigo, String ageDireccion) {
        this.ageId = ageId;
        this.ageCodigo = ageCodigo;
        this.ageDireccion = ageDireccion;
    }
    public Agentes(int ageId, String ageCodigo, String ageDireccion, Double ageLatitud, Double ageLongitud, String ageFase, String ageEstado, String ageSentido, String ageTipoluz, Integer ageNorte, Integer ageSur, Integer ageEste, Integer ageOeste, String ageObservacion) {
       this.ageId = ageId;
       this.ageCodigo = ageCodigo;
       this.ageDireccion = ageDireccion;
       this.ageLatitud = ageLatitud;
       this.ageLongitud = ageLongitud;
       this.ageFase = ageFase;
       this.ageEstado = ageEstado;
       this.ageSentido = ageSentido;
       this.ageTipoluz = ageTipoluz;
       this.ageNorte = ageNorte;
       this.ageSur = ageSur;
       this.ageEste = ageEste;
       this.ageOeste = ageOeste;
       this.ageObservacion = ageObservacion;
    }
   
     @Id 

    
    @Column(name="age_id", unique=true, nullable=false)
    public int getAgeId() {
        return this.ageId;
    }
    
    public void setAgeId(int ageId) {
        this.ageId = ageId;
    }

    
    @Column(name="age_codigo", unique=true, nullable=false, length=100)
    public String getAgeCodigo() {
        return this.ageCodigo;
    }
    
    public void setAgeCodigo(String ageCodigo) {
        this.ageCodigo = ageCodigo;
    }

    
    @Column(name="age_direccion", nullable=false, length=200)
    public String getAgeDireccion() {
        return this.ageDireccion;
    }
    
    public void setAgeDireccion(String ageDireccion) {
        this.ageDireccion = ageDireccion;
    }

    
    @Column(name="age_latitud", precision=22, scale=0)
    public Double getAgeLatitud() {
        return this.ageLatitud;
    }
    
    public void setAgeLatitud(Double ageLatitud) {
        this.ageLatitud = ageLatitud;
    }

    
    @Column(name="age_longitud", precision=22, scale=0)
    public Double getAgeLongitud() {
        return this.ageLongitud;
    }
    
    public void setAgeLongitud(Double ageLongitud) {
        this.ageLongitud = ageLongitud;
    }

    
    @Column(name="age_fase", length=3)
    public String getAgeFase() {
        return this.ageFase;
    }
    
    public void setAgeFase(String ageFase) {
        this.ageFase = ageFase;
    }

    
    @Column(name="age_estado", length=100)
    public String getAgeEstado() {
        return this.ageEstado;
    }
    
    public void setAgeEstado(String ageEstado) {
        this.ageEstado = ageEstado;
    }
    
    @Column(name="age_sentido", length=40)
    public String getAgeSentido() {
        return this.ageSentido;
    }
    
    public void setAgeSentido(String ageSentido) {
        this.ageSentido = ageSentido;
    }
    
    @Column(name="age_tipoluz", length=20)
    public String getAgeTipoluz() {
        return this.ageTipoluz;
    }
    
    public void setAgeTipoluz(String ageTipoluz) {
        this.ageTipoluz = ageTipoluz;
    }

    
    @Column(name="age_norte")
    public Integer getAgeNorte() {
        return this.ageNorte;
    }
    
    public void setAgeNorte(Integer ageNorte) {
        this.ageNorte = ageNorte;
    }

    
    @Column(name="age_sur")
    public Integer getAgeSur() {
        return this.ageSur;
    }
    
    public void setAgeSur(Integer ageSur) {
        this.ageSur = ageSur;
    }

    
    @Column(name="age_este")
    public Integer getAgeEste() {
        return this.ageEste;
    }
    
    public void setAgeEste(Integer ageEste) {
        this.ageEste = ageEste;
    }

    
    @Column(name="age_oeste")
    public Integer getAgeOeste() {
        return this.ageOeste;
    }
    
    public void setAgeOeste(Integer ageOeste) {
        this.ageOeste = ageOeste;
    }

    
    @Column(name="age_observacion", length=100)
    public String getAgeObservacion() {
        return this.ageObservacion;
    }
    
    public void setAgeObservacion(String ageObservacion) {
        this.ageObservacion = ageObservacion;
    }




}


