package model;
// Generated 17/09/2014 04:18:51 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Creencias generated by hbm2java
 */
@Entity
@Table(name="creencias"
    ,catalog="bddsemaforo"
)
public class Creencias  implements java.io.Serializable {


     private int creId;
     private String creDescripcion;

    public Creencias() {
    }

    public Creencias(int creId, String creDescripcion) {
       this.creId = creId;
       this.creDescripcion = creDescripcion;
    }
   
     @Id 

    
    @Column(name="cre_id", unique=true, nullable=false)
    public int getCreId() {
        return this.creId;
    }
    
    public void setCreId(int creId) {
        this.creId = creId;
    }

    
    @Column(name="cre_descripcion", nullable=false, length=100)
    public String getCreDescripcion() {
        return this.creDescripcion;
    }
    
    public void setCreDescripcion(String creDescripcion) {
        this.creDescripcion = creDescripcion;
    }




}


