package model;
// Generated 17/09/2014 04:18:51 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Deseos generated by hbm2java
 */
@Entity
@Table(name="deseos"
    ,catalog="bddsemaforo"
)
public class Deseos  implements java.io.Serializable {


     private Integer desId;
     private String desDescripcion;

    public Deseos() {
    }

    public Deseos(String desDescripcion) {
       this.desDescripcion = desDescripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="des_id", unique=true, nullable=false)
    public Integer getDesId() {
        return this.desId;
    }
    
    public void setDesId(Integer desId) {
        this.desId = desId;
    }

    
    @Column(name="des_descripcion", nullable=false, length=100)
    public String getDesDescripcion() {
        return this.desDescripcion;
    }
    
    public void setDesDescripcion(String desDescripcion) {
        this.desDescripcion = desDescripcion;
    }




}


