package model;
// Generated 17/09/2014 04:18:51 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="bddsemaforo"
    , uniqueConstraints = {@UniqueConstraint(columnNames="usu_clave"), @UniqueConstraint(columnNames="usu_nombre")} 
)
public class Usuario  implements java.io.Serializable {


     private Integer usuId;
     private String usuNombre;
     private String usuClave;

    public Usuario() {
    }

    public Usuario(String usuNombre, String usuClave) {
       this.usuNombre = usuNombre;
       this.usuClave = usuClave;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="usu_id", unique=true, nullable=false)
    public Integer getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(Integer usuId) {
        this.usuId = usuId;
    }

    
    @Column(name="usu_nombre", unique=true, nullable=false, length=45)
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }

    
    @Column(name="usu_clave", unique=true, nullable=false, length=45)
    public String getUsuClave() {
        return this.usuClave;
    }
    
    public void setUsuClave(String usuClave) {
        this.usuClave = usuClave;
    }




}


